# Generated by Django 3.2.9 on 2021-11-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Alumnos',
        ),
    ]
