# Generated by Django 3.2.9 on 2021-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_alter_alumnos_no_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='No_control',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
